export * from './dashbord/Dashboart'
export * from './pessoas/ListagemDePessoas'
export * from './pessoas/DetalheDePesoas'
export * from './cidades/DetalheDeCidades'
export * from './cidades/ListagemDeCidades'